name: Deploy to o2switch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get runner's public IP
        id: ip
        run: echo "ipv4=$(curl -s https://api.ipify.org)" >> $GITHUB_OUTPUT

      - name: Supprimer toutes les IPs en liste blanche
        run: |
          curl -sm 45 -H 'Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}' \
          'https://${{ secrets.CPANEL_SERVER }}:2083/execute/SshWhitelist/remove_all'

      - name: Ajouter l'IP du runner en liste blanche
        run: |
          curl -sm 45 -H 'Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}' \
          'https://${{ secrets.CPANEL_SERVER }}:2083/execute/SshWhitelist/add?address=${{ steps.ip.outputs.ipv4 }}&port=22'

      - name: Installer la clé SSH
        run: |
                mkdir -p ~/.ssh
                chmod 700 ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > ~/.ssh/id_rsa
                chmod 0400 ~/.ssh/id_rsa

      - name: Déployer via SSH
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.CPANEL_SERVER }} "cd preprod.spiphoto.fr/wp-content/themes/spiphoto && git pull origin main"

      - name: Nettoyer les clés SSH
        if: always()
        run: rm -fr ~/.ssh