name: Deploy to o2switch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get runner's public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Supprimer toutes les IPs en liste blanche
        run: |
          curl -sm 45 -H 'Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}' \
          'https://${{ secrets.CPANEL_SERVER }}:2083/execute/SshWhitelist/remove_all'

      - name: Ajouter l'IP du runner en liste blanche
        run: |
          curl -sm 45 -H 'Authorization: cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}' \
          'https://${{ secrets.CPANEL_SERVER }}:2083/execute/SshWhitelist/add?address=${{ steps.ip.outputs.ipv4 }}&port=22'

      - name: Installer la clé SSH
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 0400 ~/.ssh/id_rsa

      - name: Déployer via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd public_html/wp-content/themes/spiphoto
            git pull origin main

      - name: Nettoyer les clés SSH
        if: always()
        run: rm -fr ~/.ssh